name: 'spotify_dbt'
version: '1.0.0'
profile: 'spotify_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  spotify_dbt:
    staging:
      +schema: staging
      

    analytics:
      +schema: analytics
      

      dim:
        +schema: analytics
        



