from airflow import DAG
from airflow.operators.bash import BashOperator
from airflow.operators.email import EmailOperator
from airflow.utils.dates import days_ago
from airflow.utils.trigger_rule import TriggerRule
from airflow.operators.python import PythonOperator
import glob
import os
from datetime import timedelta
from airflow.models import Variable

DEFAULT_EMAIL = "thiru.kumaran.1808@gmail.com"  # Replace with your email


def check_run_limit(**context):
    count = int(Variable.get("spotify_pipeline_run_count", default_var=0))
    if count >= 10:
        raise ValueError("Max 3 runs reached. Stopping DAG.")
    Variable.set("spotify_pipeline_run_count", count + 1)




def send_success_email_with_dbt_counts(**context):
    # Locate the latest row count log file
    log_dir = "codebase/Proj_Spotify/logs/dbt/dbt_count_logs"
    files = sorted(glob.glob(f"{log_dir}/dbt_row_counts_*.log"), key=os.path.getmtime, reverse=True)
    
    if not files:
        row_counts = "❌ No row count logs found."
    else:
        with open(files[0], "r") as f:
            row_counts = f.read()

    email = EmailOperator(
        task_id='send_success_email',
        to=DEFAULT_EMAIL,
        subject='✅ Spotify Data Pipeline: SUCCESS',
        html_content=f"""
        <h2>✅ Pipeline completed successfully</h2>
        <h3>📊 DBT Row Counts:</h3>
        <pre>{row_counts}</pre>
        <h3>📂 Latest Row Count Log:</h3>
        <p>{files[0]}</p>
        <p>Check the Airflow UI for detailed logs.</p>
        <p>Thank you for using the Spotify Data Pipeline!</p>
        <p>Best regards,<br>Jiraiya</p>
        <p><strong>Note:</strong> This email is automatically generated by the Airflow DAG.</p>
        """,
    )
    email.execute(context=context)

default_args = {
    'owner': 'jiraiya',
    'email': [DEFAULT_EMAIL],
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
}

dag = DAG(
    dag_id='spotify_data_pipeline',
    default_args=default_args,
    description='End-to-end Spotify pipeline: JSON -> Parquet -> Snowflake -> DBT',
    schedule_interval= None,  # Can be cron later
    start_date=days_ago(1),
    catchup=False,
    tags=['spotify', 'pyspark', 'snowflake', 'dbt'],
    max_active_runs=1,
    concurrency=2
)

check_limit = PythonOperator(
    task_id='check_run_limit',
    python_callable=check_run_limit,
    provide_context=True,
    dag=dag
)


prepare_batch = BashOperator(
    task_id='prepare_batch',
    bash_command='codebase/Proj_Spotify/scripts/prepare_batch.sh >> codebase/Proj_Spotify/logs/batch_loader_logs/batch_loader_$(date +%Y%m%d_%H%M%S).log 2>&1',
    dag=dag
)

cleanup_after_prepare = BashOperator(
    task_id='cleanup_after_prepare',
    bash_command="""
sync && echo 3 | sudo /usr/bin/tee /proc/sys/vm/drop_caches > /dev/null || echo "⚠️ Skipping cache clear (no sudo)"
""",
    dag=dag
)

cleanup_after_json = BashOperator(
    task_id='cleanup_after_json',
    bash_command="""
sync && echo 3 | sudo /usr/bin/tee /proc/sys/vm/drop_caches > /dev/null || echo "⚠️ Skipping cache clear (no sudo)"
""",
    dag=dag
)

cleanup_after_playlists = BashOperator(
    task_id='cleanup_after_playlists',
    bash_command="""
sync && echo 3 | sudo /usr/bin/tee /proc/sys/vm/drop_caches > /dev/null || echo "⚠️ Skipping cache clear (no sudo)"
""",
    dag=dag
)


json_to_parquet = BashOperator(
    task_id='json_to_parquet',
    bash_command="""
    
    source codebase/codebase_env/bin/activate && \
    spark-submit \
      --master local[2] \
      --driver-memory 3g \
      --executor-memory 3g \
      codebase/Proj_Spotify/scripts/spotify-json-parquet.py \
      >> codebase/Proj_Spotify/logs/json_to_parquet_logs/json_to_parquet_run_$(date +%Y%m%d_%H%M%S).log 2>&1
    """,
    retries=2,
    retry_delay=timedelta(minutes=10),
    dag=dag
)


upload_playlists = BashOperator(
    task_id='upload_playlists_to_snowflake',
    bash_command='source codebase/codebase_env/bin/activate && python3 codebase/Proj_Spotify/scripts/load_parquet_to_snowflake_playlists.py >> codebase/Proj_Spotify/logs/load_playlist_logs/load_playlists_$(date +%Y%m%d_%H%M%S).log 2>&1',
    dag=dag
)

upload_tracks = BashOperator(
    task_id='upload_tracks_to_snowflake',
    bash_command='''
    source codebase/codebase_env/bin/activate && spark-submit \
    --master local[4] \
    --driver-memory 4g \
    --executor-memory 4g \
    --jars /home/jiraiya/snowflake-jdbc-3.13.22.jar,/home/jiraiya/spark-snowflake_2.13-2.13.0-spark_3.4.jar \
    codebase/Proj_Spotify/scripts/load_parquet_to_snowflake_tracks.py >> codebase/Proj_Spotify/logs/load_tracks_logs/load_tracks_$(date +%Y%m%d_%H%M%S).log 2>&1
    ''',
    dag=dag
)

dbt_staging = BashOperator(
    task_id='dbt_staging',
    bash_command='cd codebase/Proj_Spotify/spotify_dbt && dbt run --select stg_processed_playlists stg_processed_tracks >> codebase/Proj_Spotify/logs/dbt/dbt_run_logs/dbt_staging_$(date +%Y%m%d_%H%M%S).log 2>&1',
    dag=dag
)

dbt_dimensions = BashOperator(
    task_id='dbt_dimensions',
    bash_command='cd codebase/Proj_Spotify/spotify_dbt && dbt run --select dim_tracks dim_albums dim_artists dim_playlists >> codebase/Proj_Spotify/logs/dbt/dbt_run_logs/dbt_dimensions_$(date +%Y%m%d_%H%M%S).log 2>&1',
    dag=dag
)

dbt_facts = BashOperator(
    task_id='dbt_facts',
    bash_command='cd codebase/Proj_Spotify/spotify_dbt && dbt run --select fct_playlist_tracks >> codebase/Proj_Spotify/logs/dbt/dbt_run_logs/dbt_facts_$(date +%Y%m%d_%H%M%S).log 2>&1',
    dag=dag
)

dbt_dim_tests = BashOperator(
    task_id='dbt_dim_tests',
    bash_command='cd codebase/Proj_Spotify/spotify_dbt && dbt test --select dim_tracks dim_albums dim_artists dim_playlists >> codebase/Proj_Spotify/logs/dbt/dbt_test_logs/dbt_dim_tests_$(date +%Y%m%d_%H%M%S).log 2>&1',
    dag=dag
)

dbt_fact_tests = BashOperator(
    task_id='dbt_fact_tests',
    bash_command='cd codebase/Proj_Spotify/spotify_dbt && dbt test --select fct_playlist_tracks >> codebase/Proj_Spotify/logs/dbt/dbt_test_logs/dbt_fact_tests_$(date +%Y%m%d_%H%M%S).log 2>&1',
    dag=dag
)

dbt_counts = BashOperator(
    task_id='dbt_row_counts',
    bash_command='cd codebase/Proj_Spotify/spotify_dbt && dbt run-operation print_row_counts >> codebase/Proj_Spotify/logs/dbt/dbt_count_logs/dbt_row_counts_$(date +%Y%m%d_%H%M%S).log 2>&1',
    dag=dag
)

notify_success = PythonOperator(
    task_id='notify_success',
    python_callable=send_success_email_with_dbt_counts,
    provide_context=True,
    trigger_rule=TriggerRule.ALL_SUCCESS,
    dag=dag
)

notify_failure = EmailOperator(
    task_id='notify_failure',
    to=DEFAULT_EMAIL,
    subject='❌ Spotify Data Pipeline: FAILED',
    html_content='The Spotify data pipeline failed. Check logs in Airflow UI.',
    trigger_rule=TriggerRule.ONE_FAILED,
    dag=dag
)

# Define dependencies
check_limit >> prepare_batch >> cleanup_after_prepare >> json_to_parquet >> cleanup_after_json >> upload_playlists
upload_playlists >> cleanup_after_playlists >> upload_tracks
upload_tracks >> dbt_staging >> dbt_dimensions >> dbt_facts
dbt_facts >> dbt_dim_tests >> dbt_fact_tests >> dbt_counts
dbt_counts >> [notify_success, notify_failure]


